import Head from "next/head";
import Link from "next/link";
import Script from "next/script";
import { GiWinterHat, GiLovers } from "react-icons/gi";
import { FaTree, FaGifts } from "react-icons/fa";
import { BsFillCalendarFill, BsFillPeopleFill } from "react-icons/bs";
import { MdFestival } from "react-icons/md";
import { TbDiscount2 } from "react-icons/tb";

import { Splide, SplideSlide } from "@splidejs/react-splide";
import "@splidejs/splide/dist/css/themes/splide-skyblue.min.css";
import AOS from 'aos';

import 'aos/dist/aos.css'; 
import { useEffect } from "react";

// import styles from "../styles/Blog.module.css"

// import Image from "next/image";

export default function Home() {
  useEffect(()=>{
    AOS.init();
  })
  return (
    <div>
      <Head>
        <title>Trojan Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/trojanlogo.jpg" />
      </Head>

      <style jsx>
        {`
          .bgimg1 {
            background-image: url("/clothsum.avif");
          }
          .bgimg2 {
            background-image: url("/holi5.jpg");
          }
          .bgimg3 {
            background-image: url("/bgimg4.webp");
          }
          .bgimg4 {
            background-image: url("/summer1.avif");
          }
          .bgimg5 {
            background-image: url("/bgimg6.webp");
          }
          .bgimg6 {
            background-image: url("/bgimg7.webp");
          }
          .bgimg7 {
            background-image: url("/bgimg8.webp");
          }
          .bgimg8 {
            background-image: url("/holi1.avif");
          }
          .bgimg9 {
            background-image: url("/sale1.avif");
          }
          .scroll1 {
            background-image: url("/scroll1.jpg");
          }
          .scroll2 {
            background-image: url("/scroll2.jpg");
          }
          .scroll3 {
            background-image: url("/holi6.jpg");
          }
          .scroll4 {
            background-image: url("/scroll10.webp");
          }
          .scroll5 {
            background-image: url("/summer.avif");
          }
          .scroll6 {
            background-image: url("/scroll7.jpg");
          }
        `}
      </style>

      {/* <div>
        <img
          src="/trojanhome1.webp"
          alt="nothing"
          className="w-full h-54 lg:h-[600px]"
        />
      </div> */}
      <Splide>
        <SplideSlide>
          <div className="scroll6 md:h-[530px] h-52 bg-clip-padding  md:bg-cover bg-contain md:scale-y-100 scale-y-175 bg-no-repeat bg-center flex justify-center ">
            <div className="self-center w-12  md:min-w-max  animate-bounce md:h-36 md:mr-8 mr-3 h-16 md:mt-0 mt-8">
              <picture><img src="/trojan.png" alt="" /></picture>
              <span className="mx-3 text-lg md:visible invisible  font-bold font-serif ">
                Shopping Store
              </span>
            </div>
          </div>
        </SplideSlide>
        <SplideSlide>
          <div className="scroll1 md:h-[530px] h-52 bg-clip-padding bg-contain md:scale-y-125 scale-y-175 bg-no-repeat bg-center"></div>
        </SplideSlide>
        <SplideSlide>
          <div className="scroll5 md:h-[530px] h-52 bg-clip-padding  bg-cover md:scale-x-100 md:scale-y-100 scale-y-125  bg-no-repeat bg-center"></div>
        </SplideSlide>
        <SplideSlide>
          <div className="scroll2 md:h-[530px] h-52 bg-clip-padding   bg-cover  bg-no-repeat bg-center"></div>
        </SplideSlide>
        <SplideSlide>
          <div className="scroll3 md:h-[530px] h-52 bg-clip-padding  md:bg-cover bg-contain md:scale-y-100 scale-y-175  bg-no-repeat bg-center"></div>
        </SplideSlide>
        <SplideSlide>
          <div className="scroll4 md:h-[530px] h-52 bg-clip-padding  bg-cover  bg-no-repeat bg-center"></div>
        </SplideSlide>
      </Splide>

      <section className="text-gray-600 body-font">
        <div className="container px-5 pt-10 pb-12 mx-auto">
          <div className="flex flex-wrap w-full mb-10 flex-col items-center text-center" data-aos="zoom-in" data-aos-duration="3000">
            <h1 className="sm:text-3xl text-2xl  title-font mb-2 text-gray-900 font-bold font-serif">
              Shop Now In Trojanstore.com
            </h1>
            <p className="lg:w-1/2 w-full leading-relaxed text-gray-500">
              Vast variety of collections are present here to shop
            </p>
          </div>
          <div className="flex flex-wrap -m-4 ">
            <div className="xl:w-1/3 md:w-1/2 w-full  p-4 ">
              <div className="border border-gray-200 h-64 hover:animate-pulse p-6 shadow-black shadow-md rounded-lg bgimg1 bg-cover bg-center bg-clip-padding"  data-aos="flip-down" data-aos-duration="2000">
                <div className="w-10 h-10 inline-flex items-center justify-center  rounded-full bg-black  text-blue-500 mb-4">
                  <GiWinterHat className="text-lg animate-ping" />
                </div>
                <h2 className="text-xl  text-black font-extrabold title-font mb-2">
                  Summer Special Sale
                </h2>
                <p className="leading-relaxed text-black font-bold  text-base ">
                  All Variety of Summer clothes <br />
                  Available at lower prices
                </p>
              </div>
            </div>
            <div className="xl:w-1/3 md:w-1/2 w-full  p-4 " data-aos="flip-up" data-aos-duration="2000">
              <div className="border border-gray-200 h-64 hover:animate-pulse  p-6 rounded-lg bgimg2 bg-contain bg-repeat-x  bg-center bg-clip-padding shadow-black shadow-md">
                <div className="w-10 h-10 inline-flex items-center justify-center  rounded-full bg-black text-blue-500 mb-4">
                  <FaTree className="text-lg animate-ping" />
                </div>
                <h2 className="text-xl text-black font-extrabold title-font mb-2">
                  Christmas Sale
                </h2>
                <p className="leading-relaxed text-black font-bold text-base">
                  Special Gifts for Special Occassion
                </p>
              </div>
            </div>
            <div className="xl:w-1/3 md:w-1/2 w-full  p-4 " data-aos="flip-down" data-aos-duration="2000">
              <div className="border border-gray-200 h-64 hover:animate-pulse p-6 rounded-lg bgimg3 bg-cover bg-center bg-clip-padding shadow-black shadow-md">
                <div className="w-10 h-10 inline-flex items-center justify-center  rounded-full bg-black  text-blue-500 mb-4">
                  <BsFillCalendarFill className="text-base animate-ping" />
                </div>
                <h2 className="text-xl text-white font-extrabold title-font mb-2">
                  New Year Sale
                </h2>
                <p className="leading-relaxed text-white font-bold text-base">
                  Decorate your house with new <br />
                  HouseHold Products at discounted prices
                </p>
              </div>
            </div>
            <div className="xl:w-1/3 md:w-1/2 w-full  p-4 " data-aos="flip-up" data-aos-duration="2000">
              <div className="border border-gray-200 h-64  hover:animate-pulse p-6 rounded-lg bgimg4 bg-cover bg-center bg-clip-padding shadow-black shadow-md">
                <div className="w-10 h-10 inline-flex items-center justify-center  rounded-full bg-black  text-blue-500 mb-4">
                  <MdFestival className="text-lg animate-ping" />
                </div>
                <h2 className="text-xl text-black font-extrabold title-font mb-2">
                  Summer Special Sale
                </h2>
                <p className="leading-relaxed text-black font-bold text-base">
                  
                  All HouseHold Products at discounted prices
                </p>
              </div>
            </div>
            <div className="xl:w-1/3 md:w-1/2 w-full  p-4 " data-aos="flip-down" data-aos-duration="2000">
              <div className="border border-gray-200 h-64  hover:animate-pulse p-6 rounded-lg bgimg5 bg-cover bg-center bg-clip-padding shadow-black shadow-md">
                <div className="w-10 h-10 inline-flex items-center justify-center  rounded-full bg-black  text-blue-500 mb-4">
                  <FaGifts className="text-lg animate-ping" />
                </div>
                <h2 className="text-xl text-black font-extrabold title-font mb-2">
                  Special Gifts
                </h2>
                <p className="leading-relaxed text-black font-bold text-base">
                  Special Gifts for Special People <br />
                  Make the loved ones happy
                </p>
              </div>
            </div>
            <div className="xl:w-1/3 md:w-1/2 w-full  p-4 " data-aos="flip-up" data-aos-duration="2000">
              <div className="border border-gray-200 h-64 hover:animate-pulse p-6 rounded-lg bgimg6 bg-cover  bg-top bg-clip-padding shadow-black shadow-md">
                <div className="w-10 h-10 inline-flex items-center justify-center  rounded-full bg-black  text-blue-500 mb-4">
                  <BsFillPeopleFill className="text-lg animate-ping" />
                </div>
                <h2 className="text-xl text-black font-extrabold title-font mb-2">
                  Family Shopping
                </h2>
                <p className="leading-relaxed text-black font-bold text-base">
                  Shop now at Trojan Store <br />
                  All type of products are available at one place
                </p>
              </div>
            </div>
            <div className="xl:w-1/3 md:w-1/2 w-full  p-4 " data-aos="flip-down" data-aos-duration="2000">
              <div className="border border-gray-200 h-64  hover:animate-pulse p-6 rounded-lg bgimg7 bg-cover bg-center bg-clip-padding shadow-black shadow-md">
                <div className="w-10 h-10 inline-flex items-center justify-center  rounded-full bg-black  text-blue-500 mb-4">
                  <GiLovers className="text-lg animate-ping" />
                </div>
                <h2 className="text-xl text-white font-extrabold title-font mb-2">
                  Marriage Special Sale
                </h2>
                <p className="leading-relaxed text-white font-bold text-base">
                  Make your marriage special by shopping now at Trojan Store
                </p>
              </div>
            </div>
            <div className="xl:w-1/3 md:w-1/2 w-full  p-4 " data-aos="flip-up" data-aos-duration="2000">
              <div className="border border-gray-200 h-64 hover:animate-pulse p-6 rounded-lg bgimg8 bg-cover bg-center bg-clip-padding shadow-black shadow-md">
                <div className="w-10 h-10 inline-flex items-center justify-center  rounded-full bg-black  text-blue-500 mb-4">
                  <FaTree className="text-lg animate-ping" />
                </div>
                <h2 className="text-lg text-black font-bold title-font mb-2"></h2>
                <p className="leading-relaxed text-black font-semibold text-base"></p>
              </div>
            </div>
            <div className="xl:w-1/3 md:w-1/2 w-full  p-4 " data-aos="flip-down" data-aos-duration="2000">
              <div className="border border-gray-200 h-64  hover:animate-pulse p-6 rounded-lg bgimg9 bg-contain  bg-center bg-clip-padding shadow-black shadow-md">
                <div className="w-10 h-10 inline-flex items-center justify-center  rounded-full bg-black  text-blue-500 mb-4">
                  <TbDiscount2 className="text-2xl animate-ping" />
                </div>
                <h2 className="text-lg text-white font-bold title-font mb-2">
                  Friday Sale
                </h2>
                <p className="leading-relaxed text-white font-semibold text-base">
                  All Discounted Products
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
